import { describe, expect, test } from "bun:test";
import * as rng from "../src/core/rng";
import { buildGolden, compareGolden } from "./golden/golden";
import stored from "./golden/rng-1.json";

describe("golden master (frozen RNG)", () => {
  test("rng-1.json matches the live substrate exactly", () => {
    const diffs = compareGolden(stored, buildGolden(rng));
    expect(diffs).toEqual([]);
  });

  test("golden file was generated by the current RNG_VERSION", () => {
    expect((stored).rngVersion).toBe(rng.RNG_VERSION);
  });
});
