/**
 * Build presets/<slug>.json from data/cligen/par/<ghcnId>.par.
 *
 *   python scripts/fetch-cligen.py     # once; downloads + extracts the .par files
 *   bun run presets                    # this script
 *
 * Prints a per-station summary (annual T, P, computed vs assigned Köppen) so
 * disagreements are visible at build time, and writes presets/index.json.
 */
import { readdirSync } from "node:fs";
import { buildPreset, convertStation, type StationSpec } from "./convert";
import { parseCligenPar } from "./cligen-parse";

const root = new URL("../../", import.meta.url);
const manifest = (await Bun.file(new URL("stations.json", import.meta.url)).json()) as {
  dataset: { name: string; doi: string; license: string };
  stations: Array<StationSpec & { set: string; alternate?: boolean }>;
};
const parDir = new URL("data/cligen/par/", root);
const outDir = new URL("presets/", root);

let present: string[] = [];
try {
  present = readdirSync(parDir);
} catch {
  console.error(`no .par files found at ${parDir.pathname} — run: python scripts/fetch-cligen.py`);
  process.exit(1);
}

const index: Array<{ id: string; name: string; file: string; koppen: string; koppenAssigned: string; alternate: boolean; contentHash: string }> = [];
const rows: string[] = [];
let mismatches = 0;

for (const spec of manifest.stations) {
  const file = `${spec.ghcnId}.par`;
  if (!present.includes(file)) {
    console.error(`missing ${file} for ${spec.slug}`);
    process.exit(1);
  }
  const text = await Bun.file(new URL(file, parDir)).text();
  const station = parseCligenPar(text);
  const conv = convertStation(station);
  const preset = buildPreset(spec, station, conv, manifest.dataset);
  await Bun.write(new URL(`${spec.slug}.json`, outDir), JSON.stringify(preset, null, 2) + "\n");

  const mat = conv.monthlyTempC.reduce((a, b) => a + b, 0) / 12;
  const map = conv.monthlyPrecipMm.reduce((a, b) => a + b, 0);
  const wet = conv.derived.expectedWetDays.reduce((a, b) => a + b, 0);
  const flag = conv.koppenComputed === spec.koppen ? "" : "  <-- differs";
  if (flag) mismatches++;
  rows.push(
    `${spec.slug.padEnd(24)} ${station.name.padEnd(30)} ${mat.toFixed(1).padStart(6)}°C ${map.toFixed(0).padStart(6)}mm ${wet.toFixed(0).padStart(4)} wet d  assigned ${spec.koppen.padEnd(4)} computed ${conv.koppenComputed.padEnd(4)}${flag}`,
  );
  index.push({ id: preset.id, name: preset.name, file: `${spec.slug}.json`, koppen: conv.koppenComputed, koppenAssigned: spec.koppen, alternate: !!spec.alternate, contentHash: preset.contentHash });
}

await Bun.write(new URL("index.json", outDir), JSON.stringify(index, null, 2) + "\n");
// Barrel for the plugin bundle (esbuild inlines JSON imports).
const barrel = [
  "// GENERATED by scripts/build-presets/index.ts — do not edit.",
  'import type { Preset } from "../core/types";',
  ...index.map((e, i) => `import p${i} from "../../presets/${e.file}";`),
  "",
  `export const PRESETS: Preset[] = [${index.map((_, i) => `p${i} as unknown as Preset`).join(", ")}];`,
  "",
].join("\n");
await Bun.write(new URL("src/generated/presets.ts", root), barrel);

console.log(rows.join("\n"));
console.log(`\nwrote ${index.length} presets to ${outDir.pathname}; Köppen disagreements: ${mismatches}`);
