/**
 * bun run validate [--years 30]
 * Regenerates every preset against its station file and writes docs/VALIDATION.md.
 */
import { readdirSync } from "node:fs";
import type { Preset } from "../../src/core/types";
import { GENERATOR_VERSION } from "../../src/core/version";
import { loadPar, summaryTable, validatePreset, type PresetValidation } from "./validate";

const root = new URL("../../", import.meta.url);
const presetDir = new URL("presets/", root);
const parDir = new URL("test/fixtures/par/", root);
const yearsArg = process.argv.indexOf("--years");
const YEARS = yearsArg >= 0 ? Number(process.argv[yearsArg + 1]) : 30;

const presets: Preset[] = await Promise.all(
  readdirSync(presetDir)
    .filter((f) => f.endsWith(".json") && f !== "index.json")
    .map((f) => Bun.file(new URL(f, presetDir)).json() as Promise<Preset>),
);

const rows: PresetValidation[] = [];
for (const p of presets) {
  const par = await loadPar(p.source.ghcnId, parDir);
  rows.push(validatePreset(p, par, YEARS, "neutral"));
  rows.push(validatePreset(p, par, YEARS, "shipped"));
  const n = rows[rows.length - 2]!;
  const s = rows[rows.length - 1]!;
  console.log(
    `${p.id.padEnd(24)} mm ${n.annual.precipMm.gen.toFixed(0).padStart(5)}/${n.annual.precipMm.exp.toFixed(0).padStart(5)}  wet ${n.annual.wetDays.gen.toFixed(0).padStart(3)}/${n.annual.wetDays.exp.toFixed(0).padStart(3)}  Tmax±${n.worst.tmaxAbs.toFixed(2)} Tmin±${n.worst.tminAbs.toFixed(2)}  spells ${(n.worst.wetSpellRel * 100).toFixed(0)}%/${(n.worst.drySpellRel * 100).toFixed(0)}%  | shipped regimes: mm ${s.annual.precipMm.gen.toFixed(0)} wet ${s.annual.wetDays.gen.toFixed(0)}`,
  );
}

const neutral = rows.filter((r) => r.regimes === "neutral");
const shipped = rows.filter((r) => r.regimes === "shipped");
const agg = (xs: number[]) => ({ max: Math.max(...xs), mean: xs.reduce((a, b) => a + b, 0) / xs.length });
const bias = shipped.map((s, i) => ({ id: s.presetId, wet: s.annual.wetDays.gen / neutral[i]!.annual.wetDays.gen - 1, mm: s.annual.precipMm.gen / neutral[i]!.annual.precipMm.gen - 1 }));

const md = `# Validation report

Generated by \`bun run validate\` — ${GENERATOR_VERSION}, ${YEARS} years per preset, seed "validation".

Each preset is regenerated and compared against the **raw CLIGEN station file** it was built
from (\`test/fixtures/par/\`), not against its own curves. "neutral" runs with a single regime
(tests the core model); "shipped" runs with the preset's default regime set (what users get).

## Summary (neutral regimes)

${summaryTable(neutral)}

Worst-of-all: wet days ±${agg(neutral.map((r) => r.worst.wetDaysAbs)).max.toFixed(2)} d/month, precipitation ${(agg(neutral.map((r) => r.worst.precipRel)).max * 100).toFixed(0)}%,
Tmax ±${agg(neutral.map((r) => r.worst.tmaxAbs)).max.toFixed(2)} °C, Tmin ±${agg(neutral.map((r) => r.worst.tminAbs)).max.toFixed(2)} °C,
wet spells ${(agg(neutral.map((r) => r.worst.wetSpellRel)).max * 100).toFixed(0)}%, dry spells ${(agg(neutral.map((r) => r.worst.drySpellRel)).max * 100).toFixed(0)}%.

## Effect of the shipped default regimes

Annual change relative to the neutral run (positive = wetter):

| preset | wet days | precipitation |
|---|---|---|
${bias.map((b) => `| ${b.id} | ${(b.wet * 100).toFixed(1)}% | ${(b.mm * 100).toFixed(1)}% |`).join("\n")}

Mean bias: wet days ${(agg(bias.map((b) => b.wet)).mean * 100).toFixed(1)}%, precipitation ${(agg(bias.map((b) => b.mm)).mean * 100).toFixed(1)}%.

## Summary (shipped regimes)

${summaryTable(shipped)}
`;
await Bun.write(new URL("docs/VALIDATION.md", root), md);
console.log(`\nwrote docs/VALIDATION.md (${rows.length} runs)`);
